Repository works-ac/apipool, pull requests merged in 2024-11, with the labels that each got.

#4 FEAT: add basic nestjs nest setup
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  jest.config.js
  nest-cli.json
  package.json
  src/api/index.ts
  src/app/index.ts
  src/constant.ts
  src/controllers/app/index.spec.ts
  src/controllers/app/index.ts
  src/controllers/index.ts
  src/main.ts
  src/modules/app/index.ts
  src/modules/index.ts
  src/packages/exceptions/errors.exception.ts
  src/packages/index.ts
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: good first issue

#6 FEAT: added deployment file
  .dockerignore
  README.md
  captain-definition.dev
  captain-definition.prod
  docker/dockerfile.dev
  docker/dockerfile.prod
  package.json
  src/packages/exceptions/errors.exception.ts
Labels: release

#8 FIX: removed ENV entries from dockerfile
  docker/dockerfile.dev
  docker/dockerfile.prod
Labels: bug

#10 FIX: port expose issue
  docker/dockerfile.dev
  docker/dockerfile.prod
  package.json
Labels: bug

#13 FEAT/FIX: added swagger and minor changes
  README.md
  package.json
  src/api/index.ts
  src/app/index.ts
  src/config/index.ts
  src/config/swagger.config.ts
  src/constant.ts
  src/controllers/app/index.spec.ts
  src/controllers/app/index.ts
  src/docs/index.ts
  src/docs/schema.doc.ts
  yarn.lock
Labels: enhancement, refactorings

#15 FIX: swagger server issue
  src/app/index.ts
  src/config/index.ts
  src/config/swagger.config.ts
  src/constant.ts
Labels: bug

#16 FIX: swagger server issue
  src/app/index.ts
  src/config/index.ts
  src/config/swagger.config.ts
  src/constant.ts
Labels: bug

#18 FIX: update readme
  README.md
  src/app/index.ts
Labels: bug, refactorings

#20 FIX: swagger docs security
  package.json
  src/api/index.ts
  src/app/index.ts
  src/config/swagger.config.ts
  src/controllers/app/index.ts
  src/docs/index.ts
  src/i18n/index.ts
  yarn.lock
Labels: refactorings, security fix

#22 FEAT/FIX: added networking apis
  src/api/index.ts
  src/app/index.ts
  src/constant.ts
  src/controllers/app/index.spec.ts
  src/controllers/index.ts
  src/controllers/utils/networking.utils.controller.ts
  src/controllers/utils/networking.utils.spec.ts
  src/docs/index.ts
  src/docs/schema.doc.ts
  src/helpers/index.ts
  src/i18n/index.ts
  src/modules/app/index.ts
  src/modules/utils/index.ts
  src/packages/exceptions/errors.exception.ts
  src/packages/exceptions/network.exception.ts
  src/packages/index.ts
  src/packages/interceptors/response.interceptor.ts
  src/packages/pipes/response.pipe.ts
Labels: bug, enhancement

#23 MERGE REQ OF PR 21
  src/api/index.ts
  src/app/index.ts
  src/constant.ts
  src/controllers/app/index.spec.ts
  src/controllers/index.ts
  src/controllers/utils/networking.utils.controller.ts
  src/controllers/utils/networking.utils.spec.ts
  src/docs/index.ts
  src/docs/schema.doc.ts
  src/helpers/index.ts
  src/i18n/index.ts
  src/modules/app/index.ts
  src/modules/utils/index.ts
  src/packages/exceptions/errors.exception.ts
  src/packages/exceptions/network.exception.ts
  src/packages/index.ts
  src/packages/interceptors/response.interceptor.ts
  src/packages/pipes/response.pipe.ts
Labels: bug, enhancement
