Repository works-ac/apipool, pull requests merged in 2025-02, with the labels that each got.

#28 fix: fix of issue #26
  .dockerignore
  .gitignore
  Dockerfile
  captain-definition
  captain-definition.dev
  captain-definition.prod
  deploy.ps1
  docker/dockerfile.dev
  docker/dockerfile.prod
Labels: refactorings

#29 fix: minor docker expose port issue
  Dockerfile
Labels: refactorings

#30 feat: issue #27
  .eslintrc.js
  Dockerfile
  deploy.ps1
  package.json
  src/api/index.ts
  src/constant.ts
  src/controllers/app/index.spec.ts
  src/controllers/utils/networking.utils.controller.ts
  src/controllers/utils/networking.utils.spec.ts
  src/docs/index.ts
  src/docs/schema.doc.ts
  src/i18n/index.ts
  src/packages/interceptors/response.interceptor.ts
  src/packages/pipes/response.pipe.ts
  yarn.lock
Labels: enhancement

#31 merge: issue #26 & #27
  .dockerignore
  .eslintrc.js
  .gitignore
  Dockerfile
  captain-definition
  captain-definition.dev
  captain-definition.prod
  deploy.ps1
  docker/dockerfile.dev
  docker/dockerfile.prod
  package.json
  src/api/index.ts
  src/constant.ts
  src/controllers/app/index.spec.ts
  src/controllers/utils/networking.utils.controller.ts
  src/controllers/utils/networking.utils.spec.ts
  src/docs/index.ts
  src/docs/schema.doc.ts
  src/i18n/index.ts
  src/packages/interceptors/response.interceptor.ts
  src/packages/pipes/response.pipe.ts
  yarn.lock
Labels: enhancement, refactorings
